version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    command: yarn run serve